/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 73
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 12
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  aux_sym_section_header_token1 = 2,
  anon_sym_COLON = 3,
  anon_sym_RBRACK = 4,
  sym_section_name = 5,
  sym_condition = 6,
  sym_option_name = 7,
  sym_assignment = 8,
  aux_sym_value_token1 = 9,
  aux_sym_value_token2 = 10,
  sym_substitution = 11,
  sym_escape = 12,
  aux_sym_dependency_annotation_token1 = 13,
  aux_sym_continuation_token1 = 14,
  sym_comment = 15,
  sym__blank_line = 16,
  sym__newline = 17,
  sym_source_file = 18,
  sym_section = 19,
  sym_section_header = 20,
  sym_option = 21,
  sym_value = 22,
  sym_dependency_annotation = 23,
  sym_continuation = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_section_repeat1 = 26,
  aux_sym_option_repeat1 = 27,
  aux_sym_value_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [aux_sym_section_header_token1] = "section_header_token1",
  [anon_sym_COLON] = ":",
  [anon_sym_RBRACK] = "]",
  [sym_section_name] = "section_name",
  [sym_condition] = "condition",
  [sym_option_name] = "option_name",
  [sym_assignment] = "assignment",
  [aux_sym_value_token1] = "value_token1",
  [aux_sym_value_token2] = "value_token2",
  [sym_substitution] = "substitution",
  [sym_escape] = "escape",
  [aux_sym_dependency_annotation_token1] = "dependency_annotation_token1",
  [aux_sym_continuation_token1] = "continuation_token1",
  [sym_comment] = "comment",
  [sym__blank_line] = "_blank_line",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_section] = "section",
  [sym_section_header] = "section_header",
  [sym_option] = "option",
  [sym_value] = "value",
  [sym_dependency_annotation] = "dependency_annotation",
  [sym_continuation] = "continuation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_option_repeat1] = "option_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_section_header_token1] = aux_sym_section_header_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_section_name] = sym_section_name,
  [sym_condition] = sym_condition,
  [sym_option_name] = sym_option_name,
  [sym_assignment] = sym_assignment,
  [aux_sym_value_token1] = aux_sym_value_token1,
  [aux_sym_value_token2] = aux_sym_value_token2,
  [sym_substitution] = sym_substitution,
  [sym_escape] = sym_escape,
  [aux_sym_dependency_annotation_token1] = aux_sym_dependency_annotation_token1,
  [aux_sym_continuation_token1] = aux_sym_continuation_token1,
  [sym_comment] = sym_comment,
  [sym__blank_line] = sym__blank_line,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_section] = sym_section,
  [sym_section_header] = sym_section_header,
  [sym_option] = sym_option,
  [sym_value] = sym_value,
  [sym_dependency_annotation] = sym_dependency_annotation,
  [sym_continuation] = sym_continuation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_option_repeat1] = aux_sym_option_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_header_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_option_name] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_dependency_annotation_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_continuation_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_continuation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_option_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
};

static const TSCharacterRange sym_section_name_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '"'}, {'$', '9'}, {'<', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static const TSCharacterRange sym_option_name_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '9'}, {';', '<'}, {'>', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '\n', 34,
        '\r', 1,
        '$', 27,
        ':', 18,
        '=', 7,
        '[', 15,
        ']', 19,
        '\t', 16,
        ' ', 16,
        '#', 32,
        ';', 32,
      );
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead == '\r') ADVANCE(25);
      if (lookahead == '$') ADVANCE(27);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '=') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(31);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if ((!eof && set_contains(sym_section_name_character_set_1, 9, lookahead))) ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != ']') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != ']') ADVANCE(21);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 3,
        '=', 7,
        '[', 15,
        '\t', 5,
        ' ', 5,
        '#', 22,
        ';', 22,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(23);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 3,
        '=', 24,
        '[', 15,
        '\t', 4,
        ' ', 4,
        '#', 32,
        ';', 32,
        '+', 6,
        '-', 6,
      );
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_section_header_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_section_header_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != ']') ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_section_name);
      if ((!eof && set_contains(sym_section_name_character_set_1, 9, lookahead))) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_condition);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != ']') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ':' ||
          lookahead == '=' ||
          lookahead == '[' ||
          lookahead == ']' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_option_name);
      if ((!eof && set_contains(sym_option_name_character_set_1, 9, lookahead))) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_assignment);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead == '\n') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '$') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_value_token2);
      if (lookahead == '$') ADVANCE(29);
      if (lookahead == '{') ADVANCE(8);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_substitution);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_dependency_annotation_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_continuation_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__blank_line);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 13},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 9},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 10},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 11},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 13},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 11},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 9},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [aux_sym_section_header_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [aux_sym_value_token2] = ACTIONS(1),
    [sym_substitution] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [aux_sym_dependency_annotation_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [sym_section] = STATE(11),
    [sym_section_header] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym__blank_line] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(13), 1,
      aux_sym_continuation_token1,
    ACTIONS(15), 1,
      sym__blank_line,
    ACTIONS(11), 2,
      sym_option_name,
      sym_comment,
    STATE(6), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(9), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [20] = 6,
    ACTIONS(20), 1,
      sym_option_name,
    ACTIONS(22), 1,
      aux_sym_dependency_annotation_token1,
    ACTIONS(24), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym__blank_line,
    ACTIONS(18), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(8), 3,
      sym_option,
      sym_dependency_annotation,
      aux_sym_section_repeat1,
  [42] = 6,
    ACTIONS(20), 1,
      sym_option_name,
    ACTIONS(22), 1,
      aux_sym_dependency_annotation_token1,
    ACTIONS(32), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym__blank_line,
    ACTIONS(30), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(3), 3,
      sym_option,
      sym_dependency_annotation,
      aux_sym_section_repeat1,
  [64] = 5,
    ACTIONS(13), 1,
      aux_sym_continuation_token1,
    ACTIONS(38), 1,
      sym__blank_line,
    ACTIONS(11), 2,
      sym_option_name,
      sym_comment,
    STATE(9), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(9), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [84] = 5,
    ACTIONS(45), 1,
      aux_sym_continuation_token1,
    ACTIONS(48), 1,
      sym__blank_line,
    ACTIONS(43), 2,
      sym_option_name,
      sym_comment,
    STATE(6), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(41), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [104] = 5,
    ACTIONS(13), 1,
      aux_sym_continuation_token1,
    ACTIONS(55), 1,
      sym__blank_line,
    ACTIONS(53), 2,
      sym_option_name,
      sym_comment,
    STATE(2), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(51), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [124] = 6,
    ACTIONS(60), 1,
      sym_option_name,
    ACTIONS(63), 1,
      aux_sym_dependency_annotation_token1,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(69), 1,
      sym__blank_line,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(8), 3,
      sym_option,
      sym_dependency_annotation,
      aux_sym_section_repeat1,
  [146] = 5,
    ACTIONS(13), 1,
      aux_sym_continuation_token1,
    ACTIONS(76), 1,
      sym__blank_line,
    ACTIONS(74), 2,
      sym_option_name,
      sym_comment,
    STATE(6), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(72), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [166] = 5,
    ACTIONS(83), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym_value_repeat1,
    STATE(63), 1,
      sym_value,
    ACTIONS(79), 2,
      aux_sym_value_token1,
      aux_sym_value_token2,
    ACTIONS(81), 2,
      sym_substitution,
      sym_escape,
  [184] = 5,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_section_header,
    ACTIONS(87), 2,
      sym_comment,
      sym__blank_line,
    STATE(12), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [202] = 5,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    STATE(4), 1,
      sym_section_header,
    ACTIONS(94), 2,
      sym_comment,
      sym__blank_line,
    STATE(12), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [220] = 2,
    ACTIONS(99), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(97), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      aux_sym_continuation_token1,
      sym__blank_line,
  [232] = 2,
    ACTIONS(103), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [243] = 2,
    ACTIONS(107), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(105), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [254] = 2,
    ACTIONS(111), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(109), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [265] = 2,
    ACTIONS(115), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(113), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [276] = 4,
    ACTIONS(123), 1,
      sym__newline,
    STATE(18), 1,
      aux_sym_value_repeat1,
    ACTIONS(117), 2,
      aux_sym_value_token1,
      aux_sym_value_token2,
    ACTIONS(120), 2,
      sym_substitution,
      sym_escape,
  [291] = 2,
    ACTIONS(127), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(125), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [302] = 4,
    ACTIONS(133), 1,
      sym__newline,
    STATE(18), 1,
      aux_sym_value_repeat1,
    ACTIONS(129), 2,
      aux_sym_value_token1,
      aux_sym_value_token2,
    ACTIONS(131), 2,
      sym_substitution,
      sym_escape,
  [317] = 2,
    ACTIONS(137), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(135), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [328] = 2,
    ACTIONS(141), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(139), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [339] = 2,
    ACTIONS(145), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(143), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [350] = 2,
    ACTIONS(149), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(147), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [361] = 2,
    ACTIONS(153), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(151), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [372] = 3,
    ACTIONS(155), 1,
      aux_sym_section_header_token1,
    ACTIONS(157), 1,
      anon_sym_COLON,
    ACTIONS(159), 1,
      anon_sym_RBRACK,
  [382] = 3,
    ACTIONS(161), 1,
      aux_sym_section_header_token1,
    ACTIONS(163), 1,
      anon_sym_COLON,
    ACTIONS(165), 1,
      anon_sym_RBRACK,
  [392] = 3,
    ACTIONS(167), 1,
      aux_sym_section_header_token1,
    ACTIONS(169), 1,
      anon_sym_COLON,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
  [402] = 3,
    ACTIONS(163), 1,
      anon_sym_COLON,
    ACTIONS(165), 1,
      anon_sym_RBRACK,
    ACTIONS(173), 1,
      aux_sym_section_header_token1,
  [412] = 2,
    ACTIONS(175), 1,
      aux_sym_section_header_token1,
    ACTIONS(177), 1,
      sym__newline,
  [419] = 2,
    ACTIONS(179), 1,
      aux_sym_section_header_token1,
    ACTIONS(181), 1,
      sym__newline,
  [426] = 2,
    ACTIONS(183), 1,
      aux_sym_section_header_token1,
    ACTIONS(185), 1,
      anon_sym_RBRACK,
  [433] = 2,
    ACTIONS(187), 1,
      aux_sym_section_header_token1,
    ACTIONS(189), 1,
      sym_section_name,
  [440] = 2,
    ACTIONS(191), 1,
      aux_sym_section_header_token1,
    ACTIONS(193), 1,
      sym__newline,
  [447] = 2,
    ACTIONS(195), 1,
      aux_sym_section_header_token1,
    ACTIONS(197), 1,
      anon_sym_RBRACK,
  [454] = 2,
    ACTIONS(167), 1,
      aux_sym_section_header_token1,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
  [461] = 2,
    ACTIONS(199), 1,
      aux_sym_section_header_token1,
    ACTIONS(201), 1,
      sym_condition,
  [468] = 2,
    ACTIONS(203), 1,
      aux_sym_section_header_token1,
    ACTIONS(205), 1,
      sym_condition,
  [475] = 2,
    ACTIONS(207), 1,
      aux_sym_section_header_token1,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
  [482] = 2,
    ACTIONS(211), 1,
      aux_sym_section_header_token1,
    ACTIONS(213), 1,
      sym__newline,
  [489] = 2,
    ACTIONS(215), 1,
      aux_sym_section_header_token1,
    ACTIONS(217), 1,
      sym__newline,
  [496] = 2,
    ACTIONS(219), 1,
      aux_sym_section_header_token1,
    ACTIONS(221), 1,
      sym__newline,
  [503] = 2,
    ACTIONS(223), 1,
      aux_sym_section_header_token1,
    ACTIONS(225), 1,
      sym__newline,
  [510] = 2,
    ACTIONS(227), 1,
      aux_sym_section_header_token1,
    ACTIONS(229), 1,
      sym_condition,
  [517] = 1,
    ACTIONS(221), 1,
      sym__newline,
  [521] = 1,
    ACTIONS(231), 1,
      sym_condition,
  [525] = 1,
    ACTIONS(197), 1,
      anon_sym_RBRACK,
  [529] = 1,
    ACTIONS(193), 1,
      sym__newline,
  [533] = 1,
    ACTIONS(181), 1,
      sym__newline,
  [537] = 1,
    ACTIONS(233), 1,
      sym_comment,
  [541] = 1,
    ACTIONS(235), 1,
      sym__newline,
  [545] = 1,
    ACTIONS(237), 1,
      sym_comment,
  [549] = 1,
    ACTIONS(239), 1,
      sym_condition,
  [553] = 1,
    ACTIONS(241), 1,
      ts_builtin_sym_end,
  [557] = 1,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
  [561] = 1,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
  [565] = 1,
    ACTIONS(213), 1,
      sym__newline,
  [569] = 1,
    ACTIONS(217), 1,
      sym__newline,
  [573] = 1,
    ACTIONS(243), 1,
      anon_sym_RBRACK,
  [577] = 1,
    ACTIONS(245), 1,
      sym_comment,
  [581] = 1,
    ACTIONS(247), 1,
      sym_comment,
  [585] = 1,
    ACTIONS(249), 1,
      sym_assignment,
  [589] = 1,
    ACTIONS(251), 1,
      sym__newline,
  [593] = 1,
    ACTIONS(253), 1,
      sym_condition,
  [597] = 1,
    ACTIONS(255), 1,
      sym_comment,
  [601] = 1,
    ACTIONS(257), 1,
      sym_section_name,
  [605] = 1,
    ACTIONS(259), 1,
      sym_comment,
  [609] = 1,
    ACTIONS(261), 1,
      sym__newline,
  [613] = 1,
    ACTIONS(263), 1,
      sym__newline,
  [617] = 1,
    ACTIONS(265), 1,
      sym__newline,
  [621] = 1,
    ACTIONS(185), 1,
      anon_sym_RBRACK,
  [625] = 1,
    ACTIONS(267), 1,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 64,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 104,
  [SMALL_STATE(8)] = 124,
  [SMALL_STATE(9)] = 146,
  [SMALL_STATE(10)] = 166,
  [SMALL_STATE(11)] = 184,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 220,
  [SMALL_STATE(14)] = 232,
  [SMALL_STATE(15)] = 243,
  [SMALL_STATE(16)] = 254,
  [SMALL_STATE(17)] = 265,
  [SMALL_STATE(18)] = 276,
  [SMALL_STATE(19)] = 291,
  [SMALL_STATE(20)] = 302,
  [SMALL_STATE(21)] = 317,
  [SMALL_STATE(22)] = 328,
  [SMALL_STATE(23)] = 339,
  [SMALL_STATE(24)] = 350,
  [SMALL_STATE(25)] = 361,
  [SMALL_STATE(26)] = 372,
  [SMALL_STATE(27)] = 382,
  [SMALL_STATE(28)] = 392,
  [SMALL_STATE(29)] = 402,
  [SMALL_STATE(30)] = 412,
  [SMALL_STATE(31)] = 419,
  [SMALL_STATE(32)] = 426,
  [SMALL_STATE(33)] = 433,
  [SMALL_STATE(34)] = 440,
  [SMALL_STATE(35)] = 447,
  [SMALL_STATE(36)] = 454,
  [SMALL_STATE(37)] = 461,
  [SMALL_STATE(38)] = 468,
  [SMALL_STATE(39)] = 475,
  [SMALL_STATE(40)] = 482,
  [SMALL_STATE(41)] = 489,
  [SMALL_STATE(42)] = 496,
  [SMALL_STATE(43)] = 503,
  [SMALL_STATE(44)] = 510,
  [SMALL_STATE(45)] = 517,
  [SMALL_STATE(46)] = 521,
  [SMALL_STATE(47)] = 525,
  [SMALL_STATE(48)] = 529,
  [SMALL_STATE(49)] = 533,
  [SMALL_STATE(50)] = 537,
  [SMALL_STATE(51)] = 541,
  [SMALL_STATE(52)] = 545,
  [SMALL_STATE(53)] = 549,
  [SMALL_STATE(54)] = 553,
  [SMALL_STATE(55)] = 557,
  [SMALL_STATE(56)] = 561,
  [SMALL_STATE(57)] = 565,
  [SMALL_STATE(58)] = 569,
  [SMALL_STATE(59)] = 573,
  [SMALL_STATE(60)] = 577,
  [SMALL_STATE(61)] = 581,
  [SMALL_STATE(62)] = 585,
  [SMALL_STATE(63)] = 589,
  [SMALL_STATE(64)] = 593,
  [SMALL_STATE(65)] = 597,
  [SMALL_STATE(66)] = 601,
  [SMALL_STATE(67)] = 605,
  [SMALL_STATE(68)] = 609,
  [SMALL_STATE(69)] = 613,
  [SMALL_STATE(70)] = 617,
  [SMALL_STATE(71)] = 621,
  [SMALL_STATE(72)] = 625,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 4, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 4, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 4, 0, 0), SHIFT(6),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 2, 0, 0), SHIFT(8),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 2, 0, 0), SHIFT(8),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 1, 0, 0), SHIFT(3),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 1, 0, 0), SHIFT(3),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 4, 0, 0), SHIFT(9),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 3, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 3, 0, 0), SHIFT(2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 5, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 5, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 5, 0, 0), SHIFT(6),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_continuation, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 5, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 5, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 12, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 12, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_annotation, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dependency_annotation, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 6, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 6, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 9, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 9, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 7, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 7, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 8, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 8, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 10, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 10, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 11, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 11, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [241] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_buildout(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "buildout",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
