/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  aux_sym_section_header_token1 = 2,
  anon_sym_RBRACK = 3,
  sym_section_name = 4,
  sym_condition = 5,
  sym_option_name = 6,
  sym_assignment = 7,
  aux_sym_value_token1 = 8,
  aux_sym_value_token2 = 9,
  sym_substitution = 10,
  sym_escape = 11,
  aux_sym_dependency_annotation_token1 = 12,
  aux_sym_continuation_token1 = 13,
  sym_comment = 14,
  sym__blank_line = 15,
  sym__newline = 16,
  sym_source_file = 17,
  sym_section = 18,
  sym_section_header = 19,
  sym_option = 20,
  sym_value = 21,
  sym_dependency_annotation = 22,
  sym_continuation = 23,
  sym__trailing_comment = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_section_repeat1 = 26,
  aux_sym_option_repeat1 = 27,
  aux_sym_value_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [aux_sym_section_header_token1] = "section_header_token1",
  [anon_sym_RBRACK] = "]",
  [sym_section_name] = "section_name",
  [sym_condition] = "condition",
  [sym_option_name] = "option_name",
  [sym_assignment] = "assignment",
  [aux_sym_value_token1] = "value_token1",
  [aux_sym_value_token2] = "value_token2",
  [sym_substitution] = "substitution",
  [sym_escape] = "escape",
  [aux_sym_dependency_annotation_token1] = "dependency_annotation_token1",
  [aux_sym_continuation_token1] = "continuation_token1",
  [sym_comment] = "comment",
  [sym__blank_line] = "_blank_line",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_section] = "section",
  [sym_section_header] = "section_header",
  [sym_option] = "option",
  [sym_value] = "value",
  [sym_dependency_annotation] = "dependency_annotation",
  [sym_continuation] = "continuation",
  [sym__trailing_comment] = "_trailing_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_option_repeat1] = "option_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_section_header_token1] = aux_sym_section_header_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_section_name] = sym_section_name,
  [sym_condition] = sym_condition,
  [sym_option_name] = sym_option_name,
  [sym_assignment] = sym_assignment,
  [aux_sym_value_token1] = aux_sym_value_token1,
  [aux_sym_value_token2] = aux_sym_value_token2,
  [sym_substitution] = sym_substitution,
  [sym_escape] = sym_escape,
  [aux_sym_dependency_annotation_token1] = aux_sym_dependency_annotation_token1,
  [aux_sym_continuation_token1] = aux_sym_continuation_token1,
  [sym_comment] = sym_comment,
  [sym__blank_line] = sym__blank_line,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_section] = sym_section,
  [sym_section_header] = sym_section_header,
  [sym_option] = sym_option,
  [sym_value] = sym_value,
  [sym_dependency_annotation] = sym_dependency_annotation,
  [sym_continuation] = sym_continuation,
  [sym__trailing_comment] = sym__trailing_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_option_repeat1] = aux_sym_option_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_header_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_option_name] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_substitution] = {
    .visible = true,
    .named = true,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_dependency_annotation_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_continuation_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_option] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_dependency_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym__trailing_comment] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_option_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static const TSCharacterRange sym_section_name_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '"'}, {'$', '9'}, {'<', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static const TSCharacterRange sym_option_name_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '9'}, {';', '<'}, {'>', 'Z'}, {'\\', '\\'}, {'^', 'z'}, {'|', '|'},
  {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '\n', 31,
        '\r', 1,
        '$', 24,
        ':', 8,
        '=', 7,
        '[', 14,
        ']', 16,
        '\t', 15,
        ' ', 15,
        '#', 29,
        ';', 29,
      );
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead == '\r') ADVANCE(22);
      if (lookahead == '$') ADVANCE(24);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == ']') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if ((!eof && set_contains(sym_section_name_character_set_1, 9, lookahead))) ADVANCE(17);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '\n', 30,
        '\r', 3,
        '=', 7,
        '[', 14,
        '\t', 5,
        ' ', 5,
        '#', 19,
        ';', 19,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ':' &&
          lookahead != ';' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(20);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '\n', 30,
        '\r', 3,
        '=', 21,
        '[', 14,
        '\t', 4,
        ' ', 4,
        '#', 29,
        ';', 29,
        '+', 6,
        '-', 6,
      );
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_section_header_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_section_name);
      if ((!eof && set_contains(sym_section_name_character_set_1, 9, lookahead))) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_condition);
      if (lookahead == ']') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != ';') ADVANCE(8);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_option_name);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ':' ||
          lookahead == '=' ||
          lookahead == '[' ||
          lookahead == ']' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_option_name);
      if ((!eof && set_contains(sym_option_name_character_set_1, 9, lookahead))) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_assignment);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '$') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_value_token2);
      if (lookahead == '$') ADVANCE(26);
      if (lookahead == '{') ADVANCE(9);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_substitution);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_dependency_annotation_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_continuation_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__blank_line);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [aux_sym_section_header_token1] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_condition] = ACTIONS(1),
    [aux_sym_value_token2] = ACTIONS(1),
    [sym_substitution] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [aux_sym_dependency_annotation_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(36),
    [sym_section] = STATE(12),
    [sym_section_header] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym__blank_line] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(11), 1,
      sym_option_name,
    ACTIONS(13), 1,
      aux_sym_dependency_annotation_token1,
    ACTIONS(15), 1,
      sym_comment,
    ACTIONS(18), 1,
      sym__blank_line,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(3), 3,
      sym_option,
      sym_dependency_annotation,
      aux_sym_section_repeat1,
  [22] = 6,
    ACTIONS(11), 1,
      sym_option_name,
    ACTIONS(13), 1,
      aux_sym_dependency_annotation_token1,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(26), 1,
      sym__blank_line,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(4), 3,
      sym_option,
      sym_dependency_annotation,
      aux_sym_section_repeat1,
  [44] = 6,
    ACTIONS(31), 1,
      sym_option_name,
    ACTIONS(34), 1,
      aux_sym_dependency_annotation_token1,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(40), 1,
      sym__blank_line,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(4), 3,
      sym_option,
      sym_dependency_annotation,
      aux_sym_section_repeat1,
  [66] = 6,
    ACTIONS(45), 1,
      sym_option_name,
    ACTIONS(47), 1,
      aux_sym_continuation_token1,
    ACTIONS(50), 1,
      sym_comment,
    ACTIONS(53), 1,
      sym__blank_line,
    STATE(5), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(43), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [88] = 6,
    ACTIONS(58), 1,
      sym_option_name,
    ACTIONS(60), 1,
      aux_sym_continuation_token1,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym__blank_line,
    STATE(8), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(56), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [110] = 6,
    ACTIONS(60), 1,
      aux_sym_continuation_token1,
    ACTIONS(70), 1,
      sym_option_name,
    ACTIONS(72), 1,
      sym_comment,
    ACTIONS(75), 1,
      sym__blank_line,
    STATE(9), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [132] = 6,
    ACTIONS(60), 1,
      aux_sym_continuation_token1,
    ACTIONS(70), 1,
      sym_option_name,
    ACTIONS(78), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym__blank_line,
    STATE(5), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(68), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [154] = 6,
    ACTIONS(60), 1,
      aux_sym_continuation_token1,
    ACTIONS(86), 1,
      sym_option_name,
    ACTIONS(88), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym__blank_line,
    STATE(5), 2,
      sym_continuation,
      aux_sym_option_repeat1,
    ACTIONS(84), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
  [176] = 5,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 1,
      anon_sym_LBRACK,
    STATE(2), 1,
      sym_section_header,
    ACTIONS(99), 2,
      sym_comment,
      sym__blank_line,
    STATE(10), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [194] = 5,
    ACTIONS(106), 1,
      sym__newline,
    STATE(16), 1,
      aux_sym_value_repeat1,
    STATE(34), 1,
      sym_value,
    ACTIONS(102), 2,
      aux_sym_value_token1,
      aux_sym_value_token2,
    ACTIONS(104), 2,
      sym_substitution,
      sym_escape,
  [212] = 5,
    ACTIONS(5), 1,
      anon_sym_LBRACK,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_section_header,
    ACTIONS(110), 2,
      sym_comment,
      sym__blank_line,
    STATE(10), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [230] = 2,
    ACTIONS(114), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(112), 5,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      aux_sym_continuation_token1,
      sym__blank_line,
  [242] = 2,
    ACTIONS(118), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(116), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [253] = 2,
    ACTIONS(122), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(120), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [264] = 4,
    ACTIONS(128), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_value_repeat1,
    ACTIONS(124), 2,
      aux_sym_value_token1,
      aux_sym_value_token2,
    ACTIONS(126), 2,
      sym_substitution,
      sym_escape,
  [279] = 4,
    ACTIONS(136), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_value_repeat1,
    ACTIONS(130), 2,
      aux_sym_value_token1,
      aux_sym_value_token2,
    ACTIONS(133), 2,
      sym_substitution,
      sym_escape,
  [294] = 2,
    ACTIONS(140), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [305] = 2,
    ACTIONS(144), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(142), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [316] = 2,
    ACTIONS(148), 2,
      sym_option_name,
      sym_comment,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      aux_sym_dependency_annotation_token1,
      sym__blank_line,
  [327] = 4,
    ACTIONS(150), 1,
      aux_sym_section_header_token1,
    ACTIONS(152), 1,
      sym_comment,
    ACTIONS(154), 1,
      sym__newline,
    STATE(32), 1,
      sym__trailing_comment,
  [340] = 4,
    ACTIONS(150), 1,
      aux_sym_section_header_token1,
    ACTIONS(156), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym__newline,
    STATE(29), 1,
      sym__trailing_comment,
  [353] = 4,
    ACTIONS(150), 1,
      aux_sym_section_header_token1,
    ACTIONS(160), 1,
      sym_comment,
    ACTIONS(162), 1,
      sym__newline,
    STATE(38), 1,
      sym__trailing_comment,
  [366] = 2,
    ACTIONS(164), 1,
      aux_sym_section_header_token1,
    ACTIONS(166), 2,
      anon_sym_RBRACK,
      sym_condition,
  [374] = 2,
    ACTIONS(168), 1,
      aux_sym_section_header_token1,
    ACTIONS(170), 2,
      anon_sym_RBRACK,
      sym_condition,
  [382] = 1,
    ACTIONS(166), 2,
      anon_sym_RBRACK,
      sym_condition,
  [387] = 2,
    ACTIONS(172), 1,
      aux_sym_section_header_token1,
    ACTIONS(174), 1,
      sym_section_name,
  [394] = 1,
    ACTIONS(176), 2,
      anon_sym_RBRACK,
      sym_condition,
  [399] = 1,
    ACTIONS(178), 1,
      sym__newline,
  [403] = 1,
    ACTIONS(180), 1,
      sym__newline,
  [407] = 1,
    ACTIONS(182), 1,
      sym_assignment,
  [411] = 1,
    ACTIONS(162), 1,
      sym__newline,
  [415] = 1,
    ACTIONS(184), 1,
      sym__newline,
  [419] = 1,
    ACTIONS(186), 1,
      sym__newline,
  [423] = 1,
    ACTIONS(188), 1,
      sym_section_name,
  [427] = 1,
    ACTIONS(190), 1,
      ts_builtin_sym_end,
  [431] = 1,
    ACTIONS(192), 1,
      sym_comment,
  [435] = 1,
    ACTIONS(158), 1,
      sym__newline,
  [439] = 1,
    ACTIONS(194), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 66,
  [SMALL_STATE(6)] = 88,
  [SMALL_STATE(7)] = 110,
  [SMALL_STATE(8)] = 132,
  [SMALL_STATE(9)] = 154,
  [SMALL_STATE(10)] = 176,
  [SMALL_STATE(11)] = 194,
  [SMALL_STATE(12)] = 212,
  [SMALL_STATE(13)] = 230,
  [SMALL_STATE(14)] = 242,
  [SMALL_STATE(15)] = 253,
  [SMALL_STATE(16)] = 264,
  [SMALL_STATE(17)] = 279,
  [SMALL_STATE(18)] = 294,
  [SMALL_STATE(19)] = 305,
  [SMALL_STATE(20)] = 316,
  [SMALL_STATE(21)] = 327,
  [SMALL_STATE(22)] = 340,
  [SMALL_STATE(23)] = 353,
  [SMALL_STATE(24)] = 366,
  [SMALL_STATE(25)] = 374,
  [SMALL_STATE(26)] = 382,
  [SMALL_STATE(27)] = 387,
  [SMALL_STATE(28)] = 394,
  [SMALL_STATE(29)] = 399,
  [SMALL_STATE(30)] = 403,
  [SMALL_STATE(31)] = 407,
  [SMALL_STATE(32)] = 411,
  [SMALL_STATE(33)] = 415,
  [SMALL_STATE(34)] = 419,
  [SMALL_STATE(35)] = 423,
  [SMALL_STATE(36)] = 427,
  [SMALL_STATE(37)] = 431,
  [SMALL_STATE(38)] = 435,
  [SMALL_STATE(39)] = 439,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 1, 0, 0), SHIFT(3),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 1, 0, 0), SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_section, 2, 0, 0), SHIFT(4),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_section, 2, 0, 0), SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_option, 3, 0, 0), SHIFT(8),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 3, 0, 0), SHIFT(8),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 4, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_option, 4, 0, 0), SHIFT(9),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 4, 0, 0), SHIFT(9),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_option, 4, 0, 0), SHIFT(5),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 4, 0, 0), SHIFT(5),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option, 5, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_option, 5, 0, 0),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_option, 5, 0, 0), SHIFT(5),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_option, 5, 0, 0), SHIFT(5),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_continuation, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_continuation, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependency_annotation, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dependency_annotation, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 5, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 5, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 6, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 6, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 4, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 4, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 7, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 7, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [190] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__trailing_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_buildout(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "buildout",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
